// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyb-qgWBWSfgwPRwuBTt1yR1ssPbZ_Rvs',
    appId: '1:389544767613:web:c90d46446df7650abbc114',
    messagingSenderId: '389544767613',
    projectId: 'dztrainfay',
    authDomain: 'dztrainfay.firebaseapp.com',
    storageBucket: 'dztrainfay.firebasestorage.app',
    measurementId: 'G-72BRTBNPZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC219vrVdUDeWqnshGJ4FSvNCmGUhL41go',
    appId: '1:389544767613:android:f9a2ba4901433254bbc114',
    messagingSenderId: '389544767613',
    projectId: 'dztrainfay',
    storageBucket: 'dztrainfay.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaRgZ8PR4KvdGiuUuhbW6d9pPMZokX4Bw',
    appId: '1:389544767613:ios:1176133443da05b0bbc114',
    messagingSenderId: '389544767613',
    projectId: 'dztrainfay',
    storageBucket: 'dztrainfay.firebasestorage.app',
    iosBundleId: 'com.example.dztrainfay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaRgZ8PR4KvdGiuUuhbW6d9pPMZokX4Bw',
    appId: '1:389544767613:ios:1176133443da05b0bbc114',
    messagingSenderId: '389544767613',
    projectId: 'dztrainfay',
    storageBucket: 'dztrainfay.firebasestorage.app',
    iosBundleId: 'com.example.dztrainfay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyb-qgWBWSfgwPRwuBTt1yR1ssPbZ_Rvs',
    appId: '1:389544767613:web:e12fc40d2a8dc215bbc114',
    messagingSenderId: '389544767613',
    projectId: 'dztrainfay',
    authDomain: 'dztrainfay.firebaseapp.com',
    storageBucket: 'dztrainfay.firebasestorage.app',
    measurementId: 'G-4ZD3XX7J95',
  );
}
